version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    insecure-external-code-execution: allow
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
    open-pull-requests-limit: 99
